# Generated by Django 3.2.19 on 2024-10-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_checkbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='checkbox',
            new_name='check2FA',
        ),
    ]
