services:

  postgres:
    image: postgres:latest
    container_name: transcendence_postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: transcendence_db
      POSTGRES_USER: transcendent
      POSTGRES_PASSWORD: '123'
    networks:
      - network

  django:
    image: django
    container_name: transcendence_django
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      # - ./frontend:/app/frontend
      - ./backend:/app/
      # - ./backend/media:/app/backend/media
    networks:
      - network
    depends_on:
      - postgres

  nginx:
    image: nginx
    container_name: transcendence_nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      # - ./frontend:/usr/share/nginx/html/static
      - ./backend/myapp/static:/usr/share/nginx/html/static
    networks:
      - network
    depends_on:
      - django

networks:
  network:
    driver: bridge
