services:

  postgres:
    image: postgres:latest
    container_name: transcendence_postgres
    expose:
      - 5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - network

  redis:
    image: redis:alpine
    container_name: transcendence_redis
    expose:
      - 6379
    networks:
      - network

  django:
    image: django
    container_name: transcendence_django
    build: ./backend
    expose:
      - 8000
    volumes:
      - ./backend:/app/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    networks:
      - network
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx
    container_name: transcendence_nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./backend/myapp/static:/usr/share/nginx/html/static
    networks:
      - network
    depends_on:
      - django

networks:
  network:
    driver: bridge
