# Generated by Django 5.1.2 on 2024-10-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_skey_2fa_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
