# Generated by Django 3.2.19 on 2024-10-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_islogged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isLogged',
        ),
    ]
